groups:
  - name: cineminha-api
    rules:
      - alert: altaTaxaDeErros
        expr: rate(http_server_requests_seconds_count{status=~"[4-5][0-9]{2}"}[1m]) > 0.7
        for: 10m
        labels:
          app: cineminha
          severity: warning
          group: backend-cineminha
          env: production
        annotations:
          title: Taxa de Erros Alta
          summary: A quantidade de erros 400 e 500 nas requisições HTTP está com uma taxa acima do normal.
          description: A quantidade de erros 400 e 500 nas requisições HTTP está com a taxa acima de 70% por mais de 10 minutos.
