version: '3.0'
services:
  cineminha:
    build: ..
    ports:
      - '8080:8080'
    hostname: cineminha
    container_name: cineminha
    volumes:
      - ../logs:/logs
    networks:
      - metricas
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    hostname: db
    container_name: db
    ports:
      - '5432:5432'
    networks:
      - metricas
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=cineminha
  prometheus:
    image: prom/prometheus
    volumes:
      - prometheus-volume:/etc/prometheus/
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - '9090:9090'
    networks:
      - metricas
    depends_on:
      - alertmanager
      - cineminha
      - db
  grafana:
    image: grafana/grafana
    volumes:
      - grafana-volume:/var/lib/grafana
    ports:
      - '3000:3000'
    networks:
      - metricas
    depends_on:
      - prometheus
      - cineminha
      - db
  alertmanager:
    image: prom/alertmanager
    restart: unless-stopped
    ports:
    - '9093:9093'
    volumes:
    - ./alertmanager.yml:/etc/alertmanager.yml
    - alertmanager-data:/etc/alertmanager/data
    command: --config.file=/etc/alertmanager.yml --log.level=debug
    networks:
      - metricas
    depends_on:
      - cineminha
      - db

volumes:
  grafana-volume:
  prometheus-volume:
  alertmanager-data:

networks:
  metricas:
    driver: bridge
