global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - 'alerts_rules1.yml'

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - 'alertmanager:9093'

scrape_configs:
  - job_name: 'cineminha'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['cineminha:8080']
